from environment import Color, Template, JapaneseColor

# color config
BORDERCOLOR = JapaneseColor.BLUES.RURI
BGCOLOR = JapaneseColor.WHITES.GEPPAKU
TEXTCOLOR = Color.BLACK
TEXTSHADOWCOLOR = Color.GRAY
COLORS = [JapaneseColor.REDS.ENJI, JapaneseColor.BLUES.RURI,
          JapaneseColor.GREENS.WAKATAKE, JapaneseColor.YELLOWS.KANZOU]
LIGHTCOLORS = [Color.change_color(c, 20) for c in COLORS]

# Keyboard config
MOVESIDEWAYSFREQ = 0.15
MOVEDOWNFREQ = 0.1

# UI config
FPS = 25
WINDOWWIDTH = 640
WINDOWHEIGHT = 480
BOXSIZE = 20
BOARDWIDTH = 15
BOARDHEIGHT = 20

XMARGIN = int((WINDOWWIDTH - BOARDWIDTH * BOXSIZE) / 2)
TOPMARGIN = WINDOWHEIGHT - (BOARDHEIGHT * BOXSIZE) - 5

TEMPLATEWIDTH = Template.TEMPLATEHEIGHT
TEMPLATEHEIGHT = Template.TEMPLATEWIDTH
BLANK = Template.BLANK
PIECES = Template.PIECES
